/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techcoffee;


import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form HomeUser
     */
    
    public void clock(){
        
        Thread clock=new Thread(){
            public void run(){
                try{
                   for(;;){
                        Calendar call =new GregorianCalendar();
                        int thu=call.get(Calendar.DAY_OF_WEEK);
                        int day=call.get(Calendar.DAY_OF_MONTH);
                        int month=call.get(Calendar.MONTH)+1;
                        int year=call.get(Calendar.YEAR);
                        int year1=call.get(Calendar.AM_PM);//Test sau 
                        int second=call.get(Calendar.SECOND);
                        int minute=call.get(Calendar.MINUTE);
                        int hour=call.get(Calendar.HOUR_OF_DAY);
                        if(thu==1)
                            lbThu.setText("Chủ Nhật");
                        else
                            lbThu.setText("Thứ: "+thu);
                        
                        if(minute>=0 && minute <=9 )
                                lbTime.setText(""+hour+":0"+minute);
                        else
                            lbTime.setText(""+hour+":"+minute);
                        
                         if(hour >=0 && hour <=9)
                             if(minute>=0 && minute <=9 )
                                lbTime.setText("0"+hour+":0"+minute);
                             else
                                lbTime.setText("0"+hour+":"+minute);
                       
                           
                        
                        lbDay.setText(""+day+"-"+month+"-"+year);
                        
                        if(hour >=5 && hour <=10)
                            lbWelcome.setText("Tôtô xin chúc quý khách buổi sáng vui vẻ !");
                        else if(hour >10 && hour <=3)
                            lbWelcome.setText("Tôtô xin chúc quý khách buổi trưa vui vẻ !");
                        else if(hour >3 && hour <=6)
                            lbWelcome.setText("Tôtô xin chúc quý khách buổi chiều vui vẻ !");
                        else 
                            lbWelcome.setText("Tôtô xin chúc quý khách buổi tối hạnh phúc !");
                        
                        
                        sleep(1000);
                   }
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
            }
        };
        
        clock.start();
        
    }
    

    public HomeUser() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbThu4 = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbThu2 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        lbThu5 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbThu3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbNameUser = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbThu = new javax.swing.JLabel();
        lbDay = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        lbStaff = new javax.swing.JLabel();
        btnDailyCheck = new javax.swing.JButton();
        lbOrder = new javax.swing.JLabel();
        lbDailyCheckin = new javax.swing.JLabel();
        lbHDSD = new javax.swing.JLabel();
        btnContact = new javax.swing.JButton();
        lbContact = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbOrder3 = new javax.swing.JLabel();
        lbOrder2 = new javax.swing.JLabel();
        lbWelcome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(32, 90, 180));
        topPanel.setForeground(new java.awt.Color(255, 255, 255));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_4.setBackground(new java.awt.Color(32, 90, 180));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });
        btn_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btn_4.add(ind_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 3));

        lbThu4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbThu4.setForeground(new java.awt.Color(255, 255, 255));
        lbThu4.setText("USER");
        btn_4.add(lbThu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        topPanel.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 110, 50));

        btn_2.setBackground(new java.awt.Color(45, 57, 80));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });
        btn_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_2.setPreferredSize(new java.awt.Dimension(42, 3));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btn_2.add(ind_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 3));

        lbThu2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbThu2.setForeground(new java.awt.Color(255, 255, 255));
        lbThu2.setText("HOME");
        btn_2.add(lbThu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2, -1, 50));

        topPanel.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 120, 50));

        btn_5.setBackground(new java.awt.Color(32, 90, 180));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_5MousePressed(evt);
            }
        });
        btn_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btn_5.add(ind_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 3));

        lbThu5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbThu5.setForeground(new java.awt.Color(255, 255, 255));
        lbThu5.setText("Profile");
        btn_5.add(lbThu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        topPanel.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 110, 50));

        btn_3.setBackground(new java.awt.Color(32, 90, 180));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });
        btn_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btn_3.add(ind_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 3));

        lbThu3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbThu3.setForeground(new java.awt.Color(255, 255, 255));
        lbThu3.setText("Setting");
        btn_3.add(lbThu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        topPanel.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 110, 50));

        btnExit.setBackground(new java.awt.Color(32, 90, 180));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-turnoff.png"))); // NOI18N
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.setBorderPainted(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        topPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 70, 50));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jPanel3.setBackground(new java.awt.Color(32, 90, 180));

        jPanel4.setBackground(new java.awt.Color(97, 136, 198));

        jPanel5.setBackground(new java.awt.Color(32, 56, 151));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-avatar.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-calendar.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-padlock.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-giftbox.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-notiffi.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(23, 23, 23))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-user.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-logout.png"))); // NOI18N

        lbNameUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNameUser.setText("NameUser");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNameUser)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbTime.setFont(new java.awt.Font("SansSerif", 0, 42)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 255, 255));
        lbTime.setText(" Clock");

        lbThu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbThu.setForeground(new java.awt.Color(255, 255, 255));
        lbThu.setText("Thu");

        lbDay.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbDay.setForeground(new java.awt.Color(255, 255, 255));
        lbDay.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThu)
                    .addComponent(lbDay))
                .addGap(56, 56, 56)
                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 440));

        PanelHome.setBackground(new java.awt.Color(255, 255, 255));
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-order.png"))); // NOI18N
        btnOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrder.setBorderPainted(false);
        PanelHome.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 100));

        btnGuide.setBackground(new java.awt.Color(255, 255, 255));
        btnGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-guide.png"))); // NOI18N
        btnGuide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuide.setBorderPainted(false);
        PanelHome.add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, 100));

        lbStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-staff.png"))); // NOI18N
        PanelHome.add(lbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 150));

        btnDailyCheck.setBackground(new java.awt.Color(255, 255, 255));
        btnDailyCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-dailycheck.png"))); // NOI18N
        btnDailyCheck.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDailyCheck.setBorderPainted(false);
        PanelHome.add(btnDailyCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, 100));

        lbOrder.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 1, 14)); // NOI18N
        lbOrder.setText("Đặt Bàn");
        PanelHome.add(lbOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, 30));

        lbDailyCheckin.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 1, 14)); // NOI18N
        lbDailyCheckin.setText("Tích Điểm ");
        PanelHome.add(lbDailyCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 90, 30));

        lbHDSD.setFont(new java.awt.Font("Noto Sans CJK SC Bold", 1, 14)); // NOI18N
        lbHDSD.setText("Hướng Dẫn ");
        PanelHome.add(lbHDSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 100, 30));

        btnContact.setBackground(new java.awt.Color(255, 255, 255));
        btnContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-email.png"))); // NOI18N
        btnContact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContact.setBorderPainted(false);
        PanelHome.add(btnContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 130, 100));

        lbContact.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 1, 14)); // NOI18N
        lbContact.setText("Liên Hệ");
        PanelHome.add(lbContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 90, 30));

        lbWelcome.setFont(new java.awt.Font("Noto Sans CJK TC Thin", 1, 16)); // NOI18N
        lbWelcome.setText("Tôtô xin chúc quý khách có một ngày vui vẻ !");
        PanelHome.add(lbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 500, 30));

        lbOrder3.setFont(new java.awt.Font("Noto Sans CJK KR Thin", 1, 16)); // NOI18N
        lbOrder3.setText("NameUser,");
        PanelHome.add(lbOrder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 110, 30));

        lbOrder2.setFont(new java.awt.Font("Noto Sans CJK JP Thin", 1, 16)); // NOI18N
        lbOrder2.setText("Xin Chào");
        PanelHome.add(lbOrder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, 30));

        lbWelcome1.setFont(new java.awt.Font("Noto Sans CJK JP Thin", 1, 16)); // NOI18N
        lbWelcome1.setText("TechCoffe hân hạnh được phục vụ quý khách !");
        PanelHome.add(lbWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 500, 30));

        getContentPane().add(PanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
        setColor(btn_4);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_5},new JPanel[]{ind_2,ind_3,ind_5});
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MousePressed
        // TODO add your handling code here:
        setColor(btn_5);
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4},new JPanel[]{ind_2,ind_3,ind_4});
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
        setColor(btn_3);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_5,btn_4},new JPanel[]{ind_2,ind_5,ind_4});
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        // TODO add your handling code here:
        setColor(btn_2);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_4,btn_3,btn_5},new JPanel[]{ind_4,ind_3,ind_5});
    }//GEN-LAST:event_btn_2MousePressed

    //Drag window 
    int xx,xy;
    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_topPanelMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    private void setColor(JPanel pane){
        pane.setBackground(new Color(45,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators){
        for(int i=0; i<pane.length; i++){
            pane[i].setBackground(new Color(32,90,180));
        }
        for(int i=0; i<indicators.length; i++){
            indicators[i].setOpaque(false);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHome;
    private javax.swing.JButton btnContact;
    private javax.swing.JButton btnDailyCheck;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnOrder;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel btn_5;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbContact;
    private javax.swing.JLabel lbDailyCheckin;
    private javax.swing.JLabel lbDay;
    private javax.swing.JLabel lbHDSD;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JLabel lbOrder2;
    private javax.swing.JLabel lbOrder3;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbThu;
    private javax.swing.JLabel lbThu2;
    private javax.swing.JLabel lbThu3;
    private javax.swing.JLabel lbThu4;
    private javax.swing.JLabel lbThu5;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel lbWelcome1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
